### ISSUE TITLE
CleanCSSFilter cannot be invoked without 'new'

### ISSUE THREAD

**Issue by theoldcounty** [ember-cli/ember-cli-preprocess-registry#46]
The latest package.json for this module has broken our build.

Class constructor CleanCSSFilter cannot be invoked without 'new'
/src/ember/node_modules/ember-cli-preprocess-registry/preprocessors.js:112:12

**Comment by AndresCL** [comment]
Same thing here. This is the line

> 110 if (plugins.length === 0) {
> 111    var compiler = require('broccoli-clean-css');
> 112    return compiler(tree, options);
> 113  } else if (plugins.length > 1) {
> 114    throw new Error('You cannot use more than one minify-css plugin at once.');
> 115  }

**Comment by tavosansal** [comment]
Having the same issue...I can't deploy to production

**Comment by tavosansal** [comment]
Here is the stack trace:
<details>
  <summary>Error:</summary>
- stack: TypeError: Class constructor CleanCSSFilter cannot be invoked without 'new'
at module.exports.preprocessMinifyCss (/home/rof/src/github.com/CoSchedule/coschedule/web/node_modules/ember-cli-preprocess-registry/preprocessors.js:112:12)
at EmberApp.styles (/home/rof/src/github.com/CoSchedule/coschedule/web/node_modules/ember-cli/lib/broccoli/ember-app.js:1518:30)
at EmberApp.toArray (/home/rof/src/github.com/CoSchedule/coschedule/web/node_modules/ember-cli/lib/broccoli/ember-app.js:1814:12)
at EmberApp.toTree (/home/rof/src/github.com/CoSchedule/coschedule/web/node_modules/ember-cli/lib/broccoli/ember-app.js:1837:32)
at module.exports (/home/rof/src/github.com/CoSchedule/coschedule/web/ember-cli-build.js:189:14)
at Builder.setupBroccoliBuilder (/home/rof/src/github.com/CoSchedule/coschedule/web/node_modules/ember-cli/lib/models/builder.js:51:19)
at new Builder (/home/rof/src/github.com/CoSchedule/coschedule/web/node_modules/ember-cli/lib/models/builder.js:29:10)
at BuildTask.run (/home/rof/src/github.com/CoSchedule/coschedule/web/node_modules/ember-cli/lib/tasks/build.js:15:19)
at Promise.resolve.then (/home/rof/src/github.com/CoSchedule/coschedule/web/node_modules/ember-cli/lib/models/command.js:243:46)
at tryCatcher (/home/rof/src/github.com/CoSchedule/coschedule/web/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:323:19)
</details>

**Comment by Turbo87** [comment]
I've reset the `ember-cli-preprocess-registry` package on npm to v3.1.2 for now until we've figured out the cause for this.

@tavosansal I would recommend to use a npm or yarn lockfile to avoid these issues during production deploys

**Comment by tavosansal** [comment]
@Turbo87 Thanks....yeah we really should be using lock files....trying to get the ball rolling on that again at my company. We had some issues with it before.
Thank you for the prompt response!

**Comment by chriswhong** [comment]
We had the same issue, explicitly added `ember-cli-preprocess-registry: 3.1.2` to our app's package.json, and production build worked.  Now we just need to remember to remove it once this is fixed. Thanks!

**Comment by theoldcounty** [comment]
No reopen the issue - its broken the build again



moment#2.10.6 bower_components/moment
:site:emberClass constructor CleanCSSFilter cannot be invoked without 'new'
TypeError: Class constructor CleanCSSFilter cannot be invoked without 'new'
    at module.exports.preprocessMinifyCss (/opt/home/jenkins/workspace/o-have-no-default-selection-made/site/src/ember/node_modules/ember-cli-preprocess-registry/preprocessors.js:112:12)
    at EmberApp.styles (/opt/home/jenkins/workspace/o-have-no-default-selection-made/site/src/ember/node_modules/ember-cli/lib/broccoli/ember-app.js:1358:30)
    at EmberApp.toArray (/opt/home/jenkins/workspace/o-have-no-default-selection-made/site/src/ember/node_modules/ember-cli/lib/broccoli/ember-app.js:1665:12)
    at EmberApp.toTree (/opt/home/jenkins/workspace/o-have-no-default-selection-made/site/src/ember/node_modules/ember-cli/lib/broccoli/ember-app.js:1686:38)
    at module.exports (/opt/home/jenkins/workspace/o-have-no-default-selection-made/site/src/ember/ember-cli-build.js:36:13)
    at Builder.setupBroccoliBuilder (/opt/home/jenkins/workspace/o-have-no-default-selection-made/site/src/ember/node_modules/ember-cli/lib/models/builder.js:56:19)
    at new Builder (/opt/home/jenkins/workspace/o-have-no-default-selection-made/site/src/ember/node_modules/ember-cli/lib/models/builder.js:30:10)
    at BuildTask.run (/opt/home/jenkins/workspace/o-have-no-default-selection-made/site/src/ember/node_modules/ember-cli/lib/tasks/build.js:15:19)
    at Promise.resolve.then (/opt/home/jenkins/workspace/o-have-no-default-selection-made/site/src/ember/node_modules/ember-cli/lib/models/command.js:242:46)
    at tryCatch (/opt/home/jenkins/workspace/o-have-no-default-selection-made/site/src/ember/node_modules/rsvp/dist/rsvp.js:525:12)
 FAILED

**Comment by Turbo87** [comment]
the fix has not been released yet...

**Comment by balajinunna** [comment]
we included `ember-cli-preprocess-registry: 3.1.2` to our app package.json. still we face the `CleanCSSFilter cannot be invoked without 'new'. Can any one help me.

**Comment by theoldcounty** [comment]
Someone updated the package.json here 9 hours ago

**Comment by theoldcounty** [comment]
Also issue with the broccoli-persistent-filter
https://github.com/stefanpenner/broccoli-persistent-filter/issues/160

**Comment by stefanpenner** [comment]
> Someone updated the package.json here 9 hours ago

that change was pulled from NPM, as I did not realize the project was in a bad state when releasing.

**Comment by stefanpenner** [comment]
@ursm is running dbcls/sparqlist without https://github.com/dbcls/sparqlist/commit/b0870894082651243e40b64d67f291ce2b394af3 a good reproduction?

**Comment by ursm** [comment]
@stefanpenner It can be reproduced by building `2a7d955` (parent of `b087089`) in production mode. 

```
ursm@x1 ~/src/github.com/dbcls/sparqlist/frontend (2a7d955*)
$ npm run build -- -prod

> sparqlist@0.0.0 build /home/ursm/src/github.com/dbcls/sparqlist/frontend
> ember build "-prod"

Could not start watchman
Visit https://ember-cli.com/user-guide/#watchman for more info.
⠋ BuildingClass constructor CleanCSSFilter cannot be invoked without 'new'


Stack Trace and Error Report: /tmp/error.dump.0c6e20fbade24c2df5d8f99fff72a4aa.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sparqlist@0.0.0 build: `ember build "-prod"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the sparqlist@0.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/ursm/.npm/_logs/2019-02-21T16_25_20_463Z-debug.log
```
This error does not occur in `b087089`. I hope this will be of some help.

**Comment by stefanpenner** [comment]
@ursm thanks I was able to reproduce.

**Comment by ursm** [comment]
You are welcome. In the same repository, ember-cli-preprocess-registry 3.2.1 seems to work without any problems.

**Comment by stefanpenner** [comment]
@ursm sounds like ember-cli-preprocess-registry has a fix, if you re-roll your lockfile the problem is resolved. 

I believe the issue is then closed, let me know if i misunderstand.

**Comment by ursm** [comment]
@stefanpenner Yes, updating the lockfile has solved the problem. 
https://github.com/dbcls/sparqlist/commit/9f1a824b1cc1d27f8fd3a2f5904b60b67884ee67#diff-5a5c9ab19e395bff8d4fcf5da4450508R5732.
